name: Android App CD
on:
  push:
    branches:
      - main
    paths:
      - android/**

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v3.10.0
        with:
          distribution: 'adopt'
          java-version: 1.8
      - name: Assemble Release Bundle
        run: cd android && ./gradlew bundleRelease
      - name: Sign Release
        uses: r0adkll/sign-android-release@v1.0.4
        with:
          releaseDirectory: android/app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Deploy to Alpha
        uses: r0adkll/upload-google-play@v1.0.16
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: today.howoldisjava8.stockbroud
          releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
          track: alpha
