name: Discord Bot CI

on:
  push:
    paths:
      - discord-bot/**
  pull_request:
    paths:
      - discord-bot/**
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3.1.0
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v2.1.6
        with:
          key: "$GITHUB_SHA"
          path: |
            ~/discord-bot/builds
            ~/discord-bot/build
            ~/discord-bot/.gradle
      - name: Build with Gradle
        run: cd discord-bot && ./gradlew compileKotlin detektMain
